### ISSUE TITLE
Components aren't found in typescript

### ISSUE THREAD

**Issue by Franziskus1988** [ipatalas/ngComponentUtility#2]
Hi. I tried your extensions but it seems that it can't find the components in our code. We are using typescript and the registration of the components is done in another file. A example would be:

```
export let ExampleComponent: ng.IComponentOptions = {
  templateUrl: "app/ExampleComponent.html",
  controller: ExampleCtrl,
  bindings: {
    exampleBinding: '<'
  }
};
```

Do you think it would be possible to add a recognition of such a component?

**Comment by ipatalas** [comment]
Hi, I did not get the exact situation you have in your project. Can you please provide a complete example with such a component (with file names and structure)?

**Comment by stogle** [comment]
@ipatalas I think I can provide an example. We normally declare our components in a file named `xxx.component.ts`:

```
export class xxxComponent implements ng.IComponentOptions {
    public template = require("./xxx.html");
    public controller = xxxController;
    public binding: = {
        exampleBinding: "<"
    };
}
```

and register them in a file called `index.ts`:

```
angular.module("xxx", []).component("xxx", new xxxComponent())
```

(You could also declare xxxComponent as var or const, instead of class, and register it with `.component("xxx", xxxComponent`.) When the component is declared in one file and registered in another, the extension does not find it.

**Comment by ipatalas** [comment]
Hi @stogle 

already figured it out earlier but thanks for clarifying. Already working on this but it will only work when the components are imported using ES6 syntax (`import ... from ...`). At least in next version. Otherwise it would require scanning all files in the project which I'd like to avoid as long as possible (at least before implementing the extension using client-server approach).

**Comment by stogle** [comment]
That's perfect, we do import the component with ES6 syntax. Does this mean that we would set the component glob to match the index.ts file, or the component.ts file, or both?

**Comment by ipatalas** [comment]
It will have to match only the files with Angular component registration which is `index.ts` in your case. It will then follow ES6 imports to find the rest.

**Comment by ipatalas** [comment]
@Franziskus1988 and @stogle 
Can you guys check new version? Just released it and it should now finally see imported components :)

**Comment by stogle** [comment]
@ipatalas Upon upgrading the extension doesn't seem to work at all. Nothing appears in the status bar and trying to run `Refresh Components Cache` command manually shows an error:
```
command 'extension.refreshAngularComponents' not found
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:856
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:513
```
Could I be doing something wrong?

**Comment by ipatalas** [comment]
I'm not sure but perhaps you opened your workspace on a file other than TS or HTML.
Those are the only activation events for the extension for now.

I think I have to change it. It should be more user friendly I guess. I will look for a way to easily detect if opened workspace is an Angular project and then implement it in a way that it's activated then instead of relying on file extensions which is far from perfect.

For now just open a TS/HTML file and then the extension should get activated. Sorry for inconvenience.

**Comment by stogle** [comment]
That was it - the only file I had open at the time was settings.json.

By setting `ngComponents.componentGlobs` to "**/index.ts", I'm getting 45 components in the status bar. I think that means that this issue is resolved. Thanks!

I have a few errors in the developer console but the error messages aren't too helpful at the moment. A few say "There was an error analyzing index.ts". Could you possibly include the full path to the file in the error message? A few say that there was an error analyzing a particular controller but no details. Could you include the exception in the log? I see it's included for components but not for controllers: https://github.com/ipatalas/ngComponentUtility/blob/b79c47a15ced978fa17439c43c9755053b6060c5/src/utils/controller/controller.ts#L26. I can then report these as separate issues if necessary. Thanks again.

**Comment by ipatalas** [comment]
Good point. I will add this and wait for more issues to come ;-). 
Thanks for your help.

**Comment by ipatalas** [comment]
@stogle new version with improved logging is ready to be served.

It's no longer related to this issue so I'm closing this one.
