### ISSUE TITLE
Components not found in ES6 import scenarios (default export not supported)

### ISSUE THREAD

**Issue by avishnyak** [ipatalas/ngComponentUtility#25]
Our components are defined in this fashion and that causes ngComponentUtility to not pick them up.  My guess is that splitting the controller configuration block and the ```.component``` trigger into different files is the root cause.

**timeline.component.js**
```js
class TimelineController {
    /* @ngInject */
   constructor() {
       // ...
    }
}

let mpTimeline = {
  templateUrl: 'public/templates/shared/timeline/timeline.component.html',
  controller: TimelineController,
  bindings: {
    dates: '<',
  }
}

export default mpTimeline
```

**timeline.module.js**
```js
import mpTimeline from './timeline.component';

export default angular.module('mpShared', [])
    .component('mpTimeline', mpTimeline)
```

**Comment by ipatalas** [comment]
How do you define `ngComponents.componentGlobs`? It should point to the files where components are registered in angular. In this case that would be the **timeline.module.js**
It should handle ES6 imports from there.

**Comment by avishnyak** [comment]
This is what my componentGlobs looks like in user settings.

```js
    "ngComponents.componentGlobs": [
        "**/*.component.js",
        "**/*.module.js"
    ],
```

**Comment by ipatalas** [comment]
Yes, it should and it does. However it seems like it doesn't support default exports yet...
I did quick workaround for that:
```
export let mpTimeline = {
  templateUrl: 'public/templates/shared/timeline/timeline.component.html',
  controller: TimelineController,
  bindings: {
    dates: '<',
  }
}

export default mpTimeline
```
There are two exports now, named and default one. It should not break the code but allows the component to be picked up by the extension.
This should be relatively easy to fix.

After changing that component is picked up but still some functions don't work because the controller is not picked up this time. Did some digging and found another issue. Controllers have to be found by glob in config. They will not be automatically imported while scanning the components. You know.. too many different scenarios to implement them all at once. Luckily this seems quite easy as well.

Anyway, changed the config to:
```JSON
"ngComponents.componentGlobs": [
        "**/*.component.js",
        "**/*.module.js"
],
"ngComponents.controllerGlobs": [
	"**/*.component.js"
]
```
and voilà:
![image](https://user-images.githubusercontent.com/2623329/40513078-0538ab00-5fa5-11e8-81c2-0e423327e9ec.png)

Those are two separate problems. Adding both to Trello.
