### ISSUE TITLE
angularRoot seems is not working. 

### ISSUE THREAD

**Issue by wizardion** [ipatalas/ngComponentUtility#52]
My project contains the following structure: 

- root
  - .tmp
  - app
  - ...

there is an additional folder called `.tmp` which contains all built-in angular modules from my app (folder: `app`). 
I tried to set this option to my app folder, 
```
"ngComponents.angularRoot": "/app",
```
but it still loads all components including the `.tmp` folder. 

I even tried the following examples, but it still doesn't work: 
```
"ngComponents.angularRoot": "./app",
"ngComponents.angularRoot": "~/app",
"ngComponents.angularRoot": "/whole/path/to/project/root/app",
```

**Comment by ipatalas** [comment]
Hi,

so you want to load only components from `app` subfolder, but don't want to load any component from `.tmp`, is that correct?

`angularRoot` setting was not meant to be used for that but technically it should work because the globs are relative to the value of `angularRoot` if it's set. This setting value is not being watched so it will not reload automatically. You either have to call `Refresh Components Cache` or restart VS Code to be sure.

If that doesn't work then you can try changing the values in `ngComponents.componentGlobs`, `ngComponents.controllerGlobs`, `ngComponents.htmlGlobs`, `ngComponents.routeGlobs` and `ngComponents.directiveGlobs` (you can skip the ones you're not using) directly.
I don't know if you are using the defaults or not but anyway, the default for components is `['**/*Component.ts']` so try changing that to `['app/**/*Component.ts']`
Don't forget to call `Refresh Components Cache` command after you change the settings. Globs configuration values are being watched and should reload automatically but it was still fairly experimental and may not always work correctly. Alternatively you can restart VS Code just to be sure.

Let me know if that helped.

**Comment by wizardion** [comment]
Thank you for your response here! Your suggestion definitely works for me! I set it up as `['app/**/*Component.ts']` for `ngComponents.componentGlobs` - and everything just started to work as expected.
Thank you!
